FROM nginx:latest

COPY ssl/arzongo_uz.crt /etc/ssl/arzongo_uz.crt
COPY ssl/arzongo.uz.txt /etc/ssl/arzongo.uz.txt

#переносим файл с конфигурацией внутр контейнера nginx
COPY nginx/default.conf /etc/nginx/conf.d/default.conf