version: '3.3'

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    volumes:
      - ./../site/:/var/www
    depends_on:
      - php
    ports: 
      - 80:80

  php:
    build: 
      context: .
      dockerfile: Dockerfile-php
    volumes:
      - ./../site/:/var/www
    environment:
      MYSQL_HOST: "mysql"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "admin"
      MYSQL_DB: "crm-building"
      MYSQL_CHARSET: "utf8"
    ports:
      - 9010:9000

  mysql:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "crm-building"
    ports:
      - 3309:3306

  adminer:
    build:
      context: .
      dockerfile: Dockerfile-adminer
    ports:
      - 9000:8080

  bot:
    build:
      context: .
      dockerfile: Dockerfile-bot
    volumes:
      - ./../bot/:/app/
    ports:
      - 5001:8080